pipeline{

    agent {

            docker {
                image 'maven:3-alpine'
                args '-v /root/.m2:/root/.m2'
            }
    }

    stages {

        stage ('Compile Stage') {

            steps {


                    sh 'mvn clean install -f /var/jenkins_home/workspace/cucumber-pipline-report/jenkins-pipeline-cucumber-example'


            }
        }
    stage ('Test Stage') {

            steps {

                sh 'mvn test -f /var/jenkins_home/workspace/cucumber-pipline-report/jenkins-pipeline-cucumber-example'

            }
        }


        stage ('Cucumber Reports') {

            steps {
                sh 'cp /var/jenkins_home/workspace/cucumber-pipline-report/target/cucumber.json /var/jenkins_home/jobs/cucumber-pipline-report/builds/19/cucumber-html-reports/.cache'
                cucumber buildStatus: "UNSTABLE",
                    fileIncludePattern: "**/cucumber.json",
                    jsonReportDirectory: 'target'

            }

        }

    }

}